### ISSUE TITLE
Transaction execution failed due to issues with transaction inputs

### ISSUE THREAD

**Issue by WgoW** [naviprotocol/navi-sdk#14]
Error: Transaction execution failed due to issues with transaction inputs, please review the errors and try again: Could not find the referenced object 0xc6374c7da60746002bfee93014aeb607e023b2d6b25c9e55a152b826dbc8c1ce at version None., Could not find the referenced object 0xbb4e2f4b6205c2e2a2db47aeb4f830796ec7c005f88537ee775986639bc442fe at version None..

### env
"@mysten/sui.js": "0.54.1",
"navi-sdk": "^1.1.21",

**Comment by ComeOnOliver** [comment]
What input is this?
