### ISSUE TITLE
NAVISDKClient 

### ISSUE THREAD

**Issue by SKfraz04** [naviprotocol/navi-sdk#19]
i face some problem when i import NAVISDKClient from
 import { NAVISDKClient } from 'navi-sdk';

const client = new NAVISDKClient({ mnemonic: mnemonic, networkType: "mainnet", numberOfAccounts: 1 });

it show this error in image
<img width="630" alt="Screenshot_2024-07-31_at_11 45 56_AM" src="https://github.com/user-attachments/assets/d0966abf-8f04-4a22-b5cd-00f9746da057">

**Comment by ComeOnOliver** [comment]
Try replace mnemonic with a valid string

**Comment by SKfraz04** [comment]
Thank you for the suggestion! The issue was caused by using an invalid or undefined value for `mnemonic`. After replacing it with a valid mnemonic string, the code worked perfectly as expected.

For anyone else encountering a similar issue, make sure that the `mnemonic` value is correctly set as a string, as it's essential for the initialization of the `NAVISDKClient`.

Hope this helps!
