### ISSUE TITLE
Failed to update ProtocolPackage:

### ISSUE THREAD

**Issue by lianshus** [naviprotocol/navi-sdk#39]
when i try to depoist or borrow coin，it always failed with this error
![image](https://github.com/user-attachments/assets/0dae7b5b-afcc-4995-921e-95e98d08cb4a)
this is my code 
`import { NAVISDKClient } from 'navi-sdk';
import { Transaction } from '@mysten/sui/transactions';
import { useSignAndExecuteTransaction } from '@mysten/dapp-kit';
import { depositCoin, borrowCoin } from 'navi-sdk/dist/libs/PTB';
import { CoinInfo, Pool, PoolConfig } from "navi-sdk/dist/types";
import { pool, Sui, wUSDC } from 'navi-sdk/dist/address';

const toDepositCoin: CoinInfo = Sui;
const toBorrowCoin: CoinInfo = wUSDC;

export default function useDepositToNavi() {
    const { mutate: signAndExecute } = useSignAndExecuteTransaction();
    
    const mnemonic = process.env.NEXT_PUBLIC_MNEMNOIC;
    if (!mnemonic) {
        console.error("Mnemonic 未定义，请检查环境变量");
        return; // Return early if mnemonic is not defined
    }
    const client = new NAVISDKClient({ mnemonic, networkType: 'mainnet', numberOfAccounts: 1 });
    const account = client.accounts[0];

    // Define the depositToNavi function
    const depositToNavi = async (amount: number) => {
        let tx = new Transaction();
        let sender = account.address;
        tx.setSender(sender);

        const amountToDeposit = 1 * 10 ** toDepositCoin.decimal;
        const amountToBorrow = amount * 10 ** toBorrowCoin.decimal;

        try {

            const [suiCoin] = tx.splitCoins(tx.gas, [1_000_000_000]);

            // Deposit coin
            const suiPoolConfig: PoolConfig = pool[toDepositCoin.symbol as keyof Pool];
            await depositCoin(tx, suiPoolConfig, suiCoin, amountToDeposit);

            // Borrow coin
            const wusdcPoolConfig: PoolConfig = pool[wUSDC.symbol as keyof Pool];
            const [returnedCoin] = await borrowCoin(tx, wusdcPoolConfig, amountToBorrow);

            // Redeposit borrowed coin
            await depositCoin(tx, wusdcPoolConfig, returnedCoin, amountToBorrow);

            // Execute and handle response
            await signAndExecute({ transaction: tx });
            
        } catch (error) {
            console.error("交易过程中发生错误:", error);
        }
    };

    // Return the depositToNavi function to make it available to the component
    return depositToNavi;
}
`

**Comment by zjx-github** [comment]
i got same question

**Comment by ComeOnOliver** [comment]
Please try to use `await getLatestProtocolPackageId` from src/libs/PoolInfo?
