### ISSUE TITLE
cant use sdk to deposit sui

### ISSUE THREAD

**Issue by zjx-github** [naviprotocol/navi-sdk#50]
Failed to update ProtocolPackage:
Error: byte deserialization failed, cause by: AccountAddressParseError
when i try to deposit sui by sdk, i got this error,please help check
here is code:
const mnemonic = ""

  const client = new NAVISDKClient({
    mnemonic,
    networkType: "mainnet" || 'https://fullnode.mainnet.sui.io', 
    numberOfAccounts: 1
  }); 
  const account = client.accounts[0];
const res = await account.depositToNavi(Sui, parseInt(amount * 10 ** 9))

**Comment by ComeOnOliver** [comment]
Did you pass in real mnemonic?  Make sure you import mnemonic correctly and amount with decimals

**Comment by zjx-github** [comment]
sir i got the real mnemonic. In fact, the deposit function was normal at first, but then it suddenly reported an error.

**Comment by zjx-github** [comment]
i find the problem, cause by https://open-api.naviprotocol.io/api/package, My server ip address seems to be blocked by cloudflare
