### ISSUE TITLE
Account derived from menomic is random

### ISSUE THREAD

**Issue by unpWn4bL3** [naviprotocol/navi-sdk#8]
I'm using navi-sdk 1.1.20 ts sdk, and the account derived from same menomic is random.
The menomic is read from .env using dotenv
<img width="674" alt="截屏2024-04-25 10 59 04" src="https://github.com/naviprotocol/navi-sdk/assets/13286957/5234b611-8381-4b04-b86e-349eb5b7c453">
<img width="846" alt="截屏2024-04-25 11 24 16" src="https://github.com/naviprotocol/navi-sdk/assets/13286957/173292e8-250f-4209-af0b-e584a89ed5bb">

**Comment by ComeOnOliver** [comment]
2 steps to validate this:
1. Console.log to make sure you did get the menomic
2. Specify `{menomic: menomic}` in the NAVISDKClient configration setup

**Comment by unpWn4bL3** [comment]
> 2 steps to validate this:
> 
> 1. Console.log to make sure you did get the menomic
> 2. Specify `{menomic: menomic}` in the NAVISDKClient configration setup

a `{ mnemonic: menomic}` would fix my problem. Is this a expected behaviour or shoud it be more type issue robust?

**Comment by ComeOnOliver** [comment]
As you can see from the constructor: 
`constructor({ mnemonic = "", networkType, accountIndex = 0 }: initializeParas = {}) `
If you not specify your paras menomic is for mnemonic, it will use "" for default, which auto generate a wallet mnemonic for you
